### ISSUE TITLE
Review REST Filtering

### ISSUE THREAD

**Issue by killerbgt** [540co/eads#16]
Review and update guidance for REST filtering

**Comment by ostranme** [comment]
Correct typo for the single condition not equals (!=) example. Has the word 'filter' but needs to be 'filters'. Missing the 's'.

![screen shot 2016-09-13 at 6 39 13 pm](https://cloud.githubusercontent.com/assets/5865367/18494020/be66d9ea-79e1-11e6-87cc-ec7d136f91b1.png)

**Comment by killerbgt** [comment]
corrected typo reported by @ostranme
