### ISSUE TITLE
Create EADS repo contribution standards

### ISSUE THREAD

**Issue by treyau21** [540co/eads#2]
This includes the creation of the CONTRIBUTING.md file and filling in with the workflow to working on this repository.

**Comment by killerbgt** [comment]
@treyau21, once you update CONTRIBUTING.md, make the link in index.md be the full github url to the file, otherwise it will not link directly when being served from eads.540.co.

**Comment by risacher** [comment]
Related: need to decide on a copyright licensing regime.  Presumably this is copyright 540 right now, and gov't has unlimited rights, which means that either party could pick a license.  CC0 maybe?  http://creativecommons.org/licenses/by/4.0/ maybe?
