### ISSUE TITLE
Should we require camelCase notation for API attributes?

### ISSUE THREAD

**Issue by treyau21** [540co/eads#58]
Opening up discussion for this.... I don't think we are currently prescriptive of this in the handbook to my knowledge.

**Comment by treyau21** [comment]
Perhaps we could add a "SHOULD" clause in the handbook for camelCase notation of the resource attributes.....  I think some of the plays that use a tool reading directly from the DB (ala SlashDB) would heavily depend on the tool on whether this is practical or not.

If we add this guidance to representations (resource attributes), should we not also think of how we'd want to standardize route names.  My initial instinct is snake_case just because I think it seeeeeems like that's the more common, but I'd like to think about it more and look and see what others are typically doing.

Either way, I think establishing a standard is a good idea.

**Comment by killerbgt** [comment]
Agree on SHOULD rather than MUST for camelCase attributes.  I would says routes (URLs) should stay snake_case due to case sensitivity of some browsers/web servers.
