### ISSUE TITLE
Consider a change to responseTime

### ISSUE THREAD

**Issue by killerbgt** [540co/eads#76]
Allow responseTime (meta object) to be a formatted string "%0.6f" in seconds

**Comment by jbjonesjr** [comment]
> The ISO 8601 date/time format MUST be used YYYY-MM-DDTHH:MM:SSZ.

Similar to using a standard for date (rather than just epoch-based ms), allowing time to be in a pre-determined format (even hr mm ss if need be for long running batches) wouldn't be bad.
