### ISSUE TITLE
Use JSON, except when you don't

### ISSUE THREAD

**Issue by jbjonesjr** [540co/eads#81]
I understand the point you are trying to get across, but think this could be a bit more clear...

![image](https://cloud.githubusercontent.com/assets/533967/22903249/1001ea8c-f206-11e6-9ad6-f4819c628495.png)

I would be definitive that 
> additional formats (CSV, PDF) are allowed in addition to JSON endpoints as need requires.

This would clarify that JSON is **required** for all endpoints, but *some* endpoints can support additional response shapes.

**Comment by killerbgt** [comment]
Agreed, we will address the wording in this section.

**Comment by jbjonesjr** [comment]
:+1:
