### ISSUE TITLE
Pagination Link Header Construction

### ISSUE THREAD

**Issue by ostranme** [540co/eads#85]
Should the handbook be more explicit about Link Header construction?

If an additional URL parameters such `sort`, `filters`,  or `fields` are requested, should the Link header include the URL param as part of the pre-constructed links.

Example:
`GET /artists?sort=-name`

Response Link Header:
`<https://dev.api.jukebox.540.co/v1/artists?&sort=-name&limit=10&offset=0>; rel="first",<https://dev.api.jukebox.540.co/v1/artists?&sort=-name&limit=10&offset=110>; rel="last",<https://dev.api.jukebox.540.co/v1/artists?&sort=-name&limit=10&offset=10>; rel="next"`

**Comment by killerbgt** [comment]
@ostranme, yes the generated link headers should include all provided query params.  We'll make a note in the handbook.  Thanks!

**Comment by ostranme** [comment]
Sounds good. Thanks!
