### ISSUE TITLE
Creating Versions

### ISSUE THREAD

**Issue by ostranme** [540co/eads#89]
It might be helpful to provide a guideline for when to create a version for your API. In API development there are many ways to break compatibility and negatively impact your clients.

Suggesting to describe the factors to consider when you are trying to decide if a new version is appropriate or if a modification of an existing representation is sufficient and acceptable.

**Comment by killerbgt** [comment]
We already mention breaking changes in the Versioning section, but I'll add a bullet about modifying an existing version.
